### ISSUE TITLE
你好,能加上摄像头切换的功能吗?

### ISSUE THREAD

**Issue by yingshirun** [Werb/MediaUtils#1]
你好,能加上摄像头切换的功能吗?   我之前自己写的加上摄像头切换后,  刚录制就报start failed: -19

**Comment by werbhelius** [comment]
有时间我会加一下

**Comment by ghost** [comment]
你好，wanbo大神，同上希望您加上摄像头切换功能, 个人能力有限》。。

**Comment by werbhelius** [comment]
@yingshirun @chKatie 简单的加了一下切换摄像头的操作，不保证所有机型都能使用，但也算提供一个思路吧 代码在这里 https://github.com/Werb/MediaUtils/blob/master/app/src/main/java/com/werb/mediautilsdemo/MediaUtils.java#L373
