### ISSUE TITLE
个人的一些优化

### ISSUE THREAD

**Issue by ExcailburWei** [Werb/MediaUtils#10]
**谢谢楼主共享**
//录像取消后再录像就不会录不了像
public void record() {
        if (isRecording) {
           ....
        }
        startRecordThread();
    }

//开始录像就不会卡一下了
@Override
    public void surfaceCreated(SurfaceHolder holder) {
        mSurfaceHolder = holder;
        startPreView(holder);
        record();
        stopRecordUnSave();
    }
 public boolean deleteTargetFile(){
        startPreView(mSurfaceHolder);
        startRecordThread();
        stopRecordUnSave();
        ...
    }

//增加个释放
public void exit(){
        if(mCamera!=null)
            mCamera.release();
        if(mMediaRecorder!=null)
            mMediaRecorder.release();
    }

**Comment by Werb** [comment]
Got！
