### ISSUE TITLE
录制完之后，视频很大，如何压缩？

### ISSUE THREAD

**Issue by keyescgm** [Werb/MediaUtils#13]
录制完之后，视频很大，如何压缩？

**Comment by werbhelius** [comment]
@keyescgm 压缩视频的解决方法一般是用 c++ 的native库来处理比如ffmpeg，录制的话一般按需设置，比如微信就控制在10S内，同时分辨率也很低，这样视频质量会很小。

**Comment by keyescgm** [comment]
分辨率低的话那肯定不行，你看微信就压缩的很小~
