### ISSUE TITLE
7.0文件删除

### ISSUE THREAD

**Issue by chenghe** [Werb/MediaUtils#3]
7.0上视频和音频都会在创建之后自动删除

**Comment by werbhelius** [comment]
不会呀，有保存和撤销这两个选项，选择撤销才会删除。

**Comment by chenghe** [comment]
我这提示保存路径toast了，应该是走了default。但是打开music目录没有找到 7.0  手机一加3T

**Comment by chenghe** [comment]
但是在7.0以下的手机上没有这个问题

**Comment by werbhelius** [comment]
有呀，我也是一加3T，7.1.1 系统，刚刚测试过的

![image](https://cloud.githubusercontent.com/assets/12763277/23843419/8e809042-07f6-11e7-9549-505608c4f419.png)

![image](https://cloud.githubusercontent.com/assets/12763277/23843412/87eae336-07f6-11e7-859a-68ca01d7aa8d.png)

**Comment by chenghe** [comment]
能打开么？

**Comment by chenghe** [comment]
![screenshot_20170313-142258](https://cloud.githubusercontent.com/assets/9172749/23843739/dc19ccb8-07f8-11e7-96f1-eab6c11c0602.png)
我这显示删除了

**Comment by werbhelius** [comment]
可以呀，这好奇怪。 - -

**Comment by chenghe** [comment]
好吧。。。
